// Los mas fritos

#ifndef IPCONSTANTS_HPP
#define IPCONSTANTS_HPP

typedef enum SERVER_PORTS {
    PORT_MASTER_USERS = 14000,
    PORT_MASTER_AUTH,
    PORT_MASTER_ARDUINO,
    PORT_ARDUINO_LISTENER,
    PORT_MASTER_STORAGE,
    PORT_MASTER_LOGS,
    PORT_PROXY_LISTENER,
} SERVER_PORTS;

typedef enum SERVER_DISCOVER_PORTS {
    DISC_MASTER = 15000,
    DISC_AUTH,
    DISC_STORAGE,
    DISC_USER_LOGS,
    DISC_PROXY,
};

#endif