= Tarea01: File System
:experimental:
:nofooter:
:source-highlighter: pygments
:sectnums:
:stem: latexmath
:xrefstyle: short

Axel Rojas Retana C36944

Dario Gomez Bernal C33243

Juan Pablo Vindas C38554

Luis Eduardo Valverde Soza C18128

== Conteste las siguientes preguntas:


=== Cuáles serían los metadatos del filesystem?
Tamaño del bloque, cantidad de bloques, bloques libres, bloques ocupados, estructura del directorio raíz, estructura de nodos índice, estructura de bloques de datos, bitmap de bloques libres/ocupados.

=== Cuáles serían los metadatos de un archivo?
Nombre del archivo, tamaño, permisos, fecha, propietario, ubicación del bloque inicial, timestamps (creación, modificación, último acceso), tipo, identificador.

=== Quiero poder direccionar bloques de datos directamente?
Sí, el indice debe tener el tamaño suficiente para direccionar todos los bloques de datos del archivo, es rápido.

=== Quiero poder hacer que los archivos sean más grandes
Sí, se puede implementar un sistema de bloques indirectos para archivos grandes, aunque es más lento.

=== Cómo se implementan los folders?
Se implementa una estructura de datos que contenga los metadatos del folder y un índice con los bloques que contienen los archivos y subfolders dentro del folder.

=== Cómo se mantiene el control de permisos de acceso a archivos?
Se mantiene un sistema de permisos basado en el usuario y grupo propietario del archivo, con permisos de lectura, escritura.

=== Cómo se controla que no haya errores en el funcionamiento general del file system?
Se implementan estructuras como bitmaps para llevar el control de bloques libres y ocupados, se realiza journaling para mantener la integridad de los datos.

=== Cómo se pueden modificar los metadatos de un archivo?
Se implementaron funciones para realizar cambios en los inodos. Aspectos como el nombre, permisos y path pueden ser modificados al utilizarlas.

=== Cómo se puede conocer el tamaño de un archivo?
Para esto se tiene una fórmula: 

tamaño = tamaño de un bloque * (cantidad de bloques usados - 1) + numero de bytes utilizados en el ultimo bloque 

=== Qué estructuras de datos son indispensables?
Una estructura para el directorio raíz, una estructura para los metadatos de archivos y folders,  una estructura de nodos índice, una estructura para los bloques de datos.


== Diseño
image::images/FileSystem.svg[FileSystem, width=700]

== Código
Programe el sistema de archivos los componentes principales, la interacción entre ellos, la especificación de lo qué son y lo que hacen y la definición de lo mínimo requerido para la implementación, en un repositorio de REPL.IT, compartido con el docente, para almacenar datos de dibujos ascii según las especificaciones del proyecto de PI. Por ej:

* int buscarArchivo() // devuelve el bloque inicial del archivo, -1 en caso de fallo
* char[] Leer(archivo, int nbytes) // devuelve msj de error en caso de fallo
* bool Escribir(archivo, char [] datos) // devuelve falso en caso de fallo
* bool Renombrar(archivo, nombreNuevo) // devuelve falso en caso de fallo

== Defina la manera en la que se puede probar la funcionalidad del sistema de archivos.
Se puede probar mediante el conjunto de instrucciones implementadas en el main, las cuales permiten crear, leer y escribir archivos, así como guardarlos y cargarlos desde un archivo externo. Además, se brindan funciones para ver el directorio y la unidad del sistema, las cuales son printDirectory() y printUnidad().

== Demostración
https://drive.google.com/file/d/1TqlFyHxaA16yGUYI_JX03sWmM6Vnhvz_/view?usp=sharing[Video demostración del sistema de archivos]